### ISSUE TITLE
Levelui interface error ?

### ISSUE THREAD

**Issue by viper4595** [hij1nx/levelui#48]
Hi, 
I have a problem with leveui interface, i have attached image.
I try to run on Windows 10, Mac OS El Capitain (Hackintosh) and Ubuntu (v14)  that all installed on my laptop but the result is the same. Anyone help me ?
Plz help me, i have no time !!!!!!!!!
(My laptop has dual-card: intel Hd 4600 and Nvdia GTX 950m)
![screenshot from 2016-08-30 12 09 26](https://cloud.githubusercontent.com/assets/21328574/18076953/3f13a352-6eac-11e6-8e85-fa1be6faf98d.png)

**Comment by viper4595** [comment]
Nobody help me ????

**Comment by heapwolf** [comment]
hey, im just traveling right now. I can help with this, i've been meaning to update this project since it has become relevant to me again.

**Comment by viper4595** [comment]
Tks for your rep. I hope to hear you soon. Have a good trip !

**Comment by oprogramador** [comment]
I have the same problem.

**Comment by viper4595** [comment]
In my case, run 
$ npm install
$ cd node_modules/level/node_modules/leveldown
$ env HOME=~/.electron-gyp && node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
fix this

**Comment by fgomescg** [comment]
> In my case, run
> $ npm install
> $ cd node_modules/level/node_modules/leveldown
> $ env HOME=~/.electron-gyp && node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
> fix this

Same problem here, but this not fix to me... got this error : SESSION_MANAGER=local/BRRJOBITANL1681:@/tmp/.ICE-unix/11806,unix/BRRJOBITANL1681:/tmp/.ICE-unix/11806
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/env
module.js:487
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
