### ISSUE TITLE
error: no member named 'ForceSet' in 'v8::Object'

### ISSUE THREAD

**Issue by amazingandyyy** [hij1nx/levelui#55]
macOS, node v10.9.0, `npm install` then throws

```
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/andy/Library/Caches/node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/andy/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/andy/.nvm/versions/node/v10.9.0/bin/node" "/Users/andy/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andy/Downloads/levelui-master/node_modules/leveldown
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2019-08-16T19_47_28_500Z-debug.log
```

Any idea?

**Comment by wangyi160** [comment]
downgrade to nodejs 8.x， nodejs 10.x and above is not supported. 
it seems such problem is related to all level libraries

**Comment by Venryx** [comment]
Can confirm that switching to node 8 (for me, node 8.11.2) resolves the compilation errors from `npm install` (on Windows, for me).

For complete install instructions, on Windows, see here: https://github.com/heapwolf/levelui/issues/45#issuecomment-589908436
